# Generated by Django 5.1.2 on 2025-03-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('imagen_url', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], default='venta', max_length=10)),
                ('deposito', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'publicaciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
            ],
            options={
                'db_table': 'comentarios',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('direccion_envio', models.TextField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='prendas_alquiladas', to='users.usuario')),
                ('propietario', models.ForeignKey(db_column='propietario_id', on_delete=django.db.models.deletion.CASCADE, related_name='alquileres_realizados', to='users.usuario')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
            ],
            options={
                'db_table': 'alquileres',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('direccion_envio', models.TextField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(db_column='comprador_id', on_delete=django.db.models.deletion.CASCADE, related_name='compras_realizadas', to='users.usuario')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
                ('vendedor', models.ForeignKey(db_column='vendedor_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to='users.usuario')),
            ],
            options={
                'db_table': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_like', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_favorito', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
            ],
            options={
                'db_table': 'favoritos',
                'ordering': ['-fecha_favorito'],
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
    ]
