# Generated by Django 5.1.2 on 2025-03-07 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0002_remove_usuario_foto_perfil_remove_usuario_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='deposito',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], default='venta', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_like', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
