# Generated by Django 5.1.2 on 2025-03-21 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='colores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estilo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='publico',
            field=models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('niño', 'Niño'), ('niña', 'Niña'), ('mascota', 'Mascota')], default='mujer', max_length=10),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='talla',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
