# Generated by Django 5.1.2 on 2025-03-11 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_favorito'),
        ('users', '0002_remove_usuario_foto_perfil_remove_usuario_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='like',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion'),
        ),
        migrations.AlterField(
            model_name='like',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('usuario', 'publicacion')},
        ),
    ]
